version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/j9v3f8u1
  build:
    commands:
      - echo Building Docker image...
      - docker build -t npm .
      - echo Pushing Docker image to ECR...
      - docker tag npm:latest public.ecr.aws/j9v3f8u1/npm:latest
      - docker push public.ecr.aws/j9v3f8u1/npm:latest
  post_build:
    commands:
      - echo Build completed on date
      - echo Creating image definitions file...
      - echo '[{"name":"npmfargate","imageUri":"public.ecr.aws/j9v3f8u1/npm","containerPort":4000}]' > imagedefinitions.json

artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    imagedefinitions:
      files:
        - imagedefinitions.json
