version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/j9v3f8u1
  build:
    commands:
      - echo Building Docker image...
      - docker build -t ec2node1 .
      - echo Pushing Docker image to ECR...
      - docker tag ec2node1:latest public.ecr.aws/j9v3f8u1/ec2node1:latest
      - docker push public.ecr.aws/j9v3f8u1/ec2node1:latest
  post_build:
    commands:
      - echo Build completed on date
      - echo Creating image definitions file...
      - echo '[{"name":"snode","imageUri":"public.ecr.aws/j9v3f8u1/ec2node1","containerPort":4000}]' > imagedefinitions.json

artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    imagedefinitions:
      files:
        - imagedefinitions.json
